[config]
schemaVersion = "0.0.1"

[package]
namespace = "xilophor"
name = "Starstruck"
description = "Meteor Showers!"
websiteUrl = ""
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.13.2"

[build]
repository = "https://thunderstore.io"
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../Starstruck/bin/Release/netstandard2.1/Starstruck.dll"
target = "/BepInEx/plugins/Starstruck/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "mod" ]